"""End-to-end tests for `keys init <target>`.

Covers: stdout / single-file / marker-append write modes, --force,
--check, marker-append idempotency, no-.git-warning, aider stderr hint.
"""
from __future__ import annotations

import os
from pathlib import Path

import pytest

from keys_keeper.cli import main as cli_main
from keys_keeper.agent_rules import render


@pytest.fixture
def chdir(tmp_path, monkeypatch):
    """Run each test in an isolated tmp cwd with a git dir present
    (so the no-.git warning is suppressed by default)."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / ".git").mkdir()
    return tmp_path


def _run(*argv: str) -> int:
    return cli_main(list(argv))


# ---------------------------------------------------------------------------
# stdout target
# ---------------------------------------------------------------------------


def test_generic_writes_to_stdout(chdir, capsys):
    rc = _run("init", "generic")
    captured = capsys.readouterr()
    assert rc == 0
    assert captured.out.startswith("<!-- generated by `keys init generic`")
    # No files created.
    assert list(chdir.iterdir()) == [chdir / ".git"]


def test_stdout_flag_works_for_any_target(chdir, capsys):
    rc = _run("init", "cursor", "--stdout")
    captured = capsys.readouterr()
    assert rc == 0
    assert "alwaysApply: true" in captured.out
    # No file on disk.
    assert not (chdir / ".cursor").exists()


# ---------------------------------------------------------------------------
# single-file targets
# ---------------------------------------------------------------------------


def test_cursor_creates_file(chdir):
    rc = _run("init", "cursor")
    assert rc == 0
    out = chdir / ".cursor" / "rules" / "keys-keeper.mdc"
    assert out.exists()
    content = out.read_text(encoding="utf-8")
    assert content.startswith("---\ndescription:")
    assert "alwaysApply: true" in content


def test_cursor_refuses_to_overwrite_without_force(chdir, capsys):
    _run("init", "cursor")
    capsys.readouterr()  # drain
    rc = _run("init", "cursor")
    captured = capsys.readouterr()
    assert rc == 1
    assert "pass --force to overwrite" in captured.err


def test_cursor_force_overwrites(chdir, capsys):
    _run("init", "cursor")
    out = chdir / ".cursor" / "rules" / "keys-keeper.mdc"
    out.write_text("tampered content\n", encoding="utf-8", newline="\n")
    rc = _run("init", "cursor", "--force")
    assert rc == 0
    assert "tampered" not in out.read_text(encoding="utf-8")


def test_cline_writes_with_alphabetic_prefix(chdir):
    rc = _run("init", "cline")
    assert rc == 0
    assert (chdir / ".clinerules" / "00-keys-keeper.md").exists()


def test_out_flag_overrides_destination(chdir, tmp_path):
    custom = chdir / "custom" / "place" / "rules.mdc"
    rc = _run("init", "cursor", "--out", str(custom))
    assert rc == 0
    assert custom.exists()


# ---------------------------------------------------------------------------
# marker-append targets (aider, codex)
# ---------------------------------------------------------------------------


def test_aider_creates_conventions_md(chdir, capsys):
    rc = _run("init", "aider")
    captured = capsys.readouterr()
    assert rc == 0
    f = chdir / "CONVENTIONS.md"
    assert f.exists()
    content = f.read_text(encoding="utf-8")
    assert content.startswith(render.MARKER_BEGIN)
    assert content.rstrip().endswith(render.MARKER_END)
    # stderr hint for aider wire-up
    assert "aider --read CONVENTIONS.md" in captured.err
    assert "/read CONVENTIONS.md" in captured.err


def test_aider_preserves_existing_content(chdir):
    f = chdir / "CONVENTIONS.md"
    user_content = "# my conventions\n\nDo not use tabs.\n"
    f.write_text(user_content, encoding="utf-8", newline="\n")
    rc = _run("init", "aider")
    assert rc == 0
    out = f.read_text(encoding="utf-8")
    assert "Do not use tabs." in out
    assert render.MARKER_BEGIN in out
    assert out.count(render.MARKER_BEGIN) == 1
    assert out.count(render.MARKER_END) == 1


def test_aider_idempotent(chdir):
    _run("init", "aider")
    f = chdir / "CONVENTIONS.md"
    first = f.read_text(encoding="utf-8")
    _run("init", "aider")
    second = f.read_text(encoding="utf-8")
    assert first == second
    assert second.count(render.MARKER_BEGIN) == 1


def test_aider_replaces_only_marker_section(chdir):
    f = chdir / "CONVENTIONS.md"
    f.write_text(
        "# header\n\n"
        f"{render.MARKER_BEGIN}\n## keys-keeper\n\nOLD CONTENT\n{render.MARKER_END}\n"
        "\n# trailing user content\n",
        encoding="utf-8",
        newline="\n",
    )
    _run("init", "aider")
    out = f.read_text(encoding="utf-8")
    assert "# header" in out
    assert "# trailing user content" in out
    assert "OLD CONTENT" not in out
    assert "Storage CLI is `keys`" in out  # canonical body is now in


def test_codex_writes_agents_md(chdir, capsys):
    rc = _run("init", "codex")
    captured = capsys.readouterr()
    assert rc == 0
    assert (chdir / "AGENTS.md").exists()
    assert "AGENTS.md is auto-loaded by Codex CLI" in captured.err


# ---------------------------------------------------------------------------
# --check drift detection
# ---------------------------------------------------------------------------


def test_check_passes_on_match(chdir, capsys):
    _run("init", "cursor")
    capsys.readouterr()
    rc = _run("init", "cursor", "--check")
    captured = capsys.readouterr()
    assert rc == 0
    assert "up to date" in captured.out


def test_check_fails_on_drift(chdir, capsys):
    _run("init", "cursor")
    out = chdir / ".cursor" / "rules" / "keys-keeper.mdc"
    out.write_text(
        out.read_text(encoding="utf-8") + "\n# tampered\n",
        encoding="utf-8",
        newline="\n",
    )
    capsys.readouterr()
    rc = _run("init", "cursor", "--check")
    captured = capsys.readouterr()
    assert rc == 1
    assert "out of date" in captured.err
    assert "+# tampered" not in captured.err  # expected does NOT have it
    assert "-# tampered" in captured.err  # actual DOES — diff shows removal


def test_check_fails_when_file_missing(chdir, capsys):
    rc = _run("init", "cursor", "--check")
    captured = capsys.readouterr()
    assert rc == 1
    assert "out of date" in captured.err


def test_check_aider_marker_drift(chdir, capsys):
    _run("init", "aider")
    f = chdir / "CONVENTIONS.md"
    text = f.read_text(encoding="utf-8")
    # Inject a tampered line inside the marker block.
    text = text.replace(render.MARKER_END, "TAMPERED\n" + render.MARKER_END)
    f.write_text(text, encoding="utf-8", newline="\n")
    capsys.readouterr()
    rc = _run("init", "aider", "--check")
    captured = capsys.readouterr()
    assert rc == 1
    assert "out of date" in captured.err


def test_check_aider_no_markers_in_file(chdir, capsys):
    (chdir / "CONVENTIONS.md").write_text(
        "# someone else's conventions\n",
        encoding="utf-8",
        newline="\n",
    )
    rc = _run("init", "aider", "--check")
    captured = capsys.readouterr()
    assert rc == 1
    assert "no keys-keeper marked section" in captured.err


# ---------------------------------------------------------------------------
# no-.git warning
# ---------------------------------------------------------------------------


def test_no_git_warning(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    # No .git dir created.
    rc = _run("init", "cursor")
    captured = capsys.readouterr()
    assert rc == 0
    assert "no .git in CWD" in captured.err


def test_no_warning_when_out_given(tmp_path, monkeypatch, capsys):
    monkeypatch.chdir(tmp_path)
    rc = _run("init", "cursor", "--out", str(tmp_path / "explicit.mdc"))
    captured = capsys.readouterr()
    assert rc == 0
    assert "no .git in CWD" not in captured.err


# ---------------------------------------------------------------------------
# claude frontmatter preservation
# ---------------------------------------------------------------------------


def test_claude_preserves_custom_frontmatter(chdir):
    target = chdir / "skills" / "keys-keeper" / "SKILL.md"
    target.parent.mkdir(parents=True)
    target.write_text(
        "---\n"
        "name: my-renamed-skill\n"
        "description: My custom description that I want preserved.\n"
        "---\n"
        "old body that should be replaced\n",
        encoding="utf-8",
        newline="\n",
    )
    rc = _run("init", "claude", "--force")
    assert rc == 0
    out = target.read_text(encoding="utf-8")
    assert "name: my-renamed-skill" in out
    assert "My custom description that I want preserved." in out
    assert "old body that should be replaced" not in out
    assert "Storage CLI is `keys`" in out  # canonical body present


# ---------------------------------------------------------------------------
# Negative paths — error handling for filesystem failures + bad input.
# Tech-lead review (2026-05-09) flagged the lack of these; raw tracebacks
# instead of friendly errors are unacceptable for a public CLI surface.
# ---------------------------------------------------------------------------


@pytest.mark.skipif(os.name == "nt", reason="chmod permission bits behave differently on Windows")
def test_init_unwriteable_target_path_returns_error(chdir, capsys):
    """A read-only parent directory should fail cleanly, not crash."""
    locked = chdir / "locked"
    locked.mkdir()
    locked.chmod(0o500)
    try:
        rc = _run("init", "cursor", "--out", str(locked / "foo.mdc"))
        captured = capsys.readouterr()
        assert rc == 2
        assert "error:" in captured.err
        # readable, not a raw traceback
        assert "Traceback" not in captured.err
        assert "permission denied" in captured.err.lower() or "permission" in captured.err.lower()
    finally:
        # Restore writability so pytest can clean up.
        locked.chmod(0o700)


def test_init_out_pointing_at_directory_returns_error(chdir, capsys):
    """`--out` targeting an existing directory should fail with a friendly
    message, not 'IsADirectoryError' bubbling up."""
    a_dir = chdir / "iam-a-dir"
    a_dir.mkdir()
    rc = _run("init", "cursor", "--out", str(a_dir))
    captured = capsys.readouterr()
    assert rc == 2
    assert "error:" in captured.err
    assert "Traceback" not in captured.err
    assert "directory" in captured.err.lower()


def test_init_aider_malformed_marker_does_not_corrupt(chdir):
    """If CONVENTIONS.md has an orphan BEGIN marker (no matching END),
    init must not crash and must produce a file with at least one valid
    BEGIN/END pair (a follow-up init will be idempotent against it)."""
    f = chdir / "CONVENTIONS.md"
    f.write_text(
        f"# user content\n\n{render.MARKER_BEGIN}\n## old stuff with no end marker\n",
        encoding="utf-8",
        newline="\n",
    )
    rc = _run("init", "aider")
    assert rc == 0
    out = f.read_text(encoding="utf-8")
    # User content survives.
    assert "# user content" in out
    # At least one valid BEGIN/END pair now exists (the freshly appended section).
    assert render.MARKER_END in out
    # Second run should now be idempotent (we have a clean pair to splice).
    second = _run("init", "aider")
    assert second == 0


def test_init_claude_malformed_frontmatter_falls_back_to_defaults(chdir):
    """If skills/keys-keeper/SKILL.md has unparseable frontmatter (no
    closing fence), claude render must fall back to canonical defaults
    rather than crashing or preserving garbage."""
    target = chdir / "skills" / "keys-keeper" / "SKILL.md"
    target.parent.mkdir(parents=True)
    # Frontmatter opens with `---` but never closes.
    target.write_text(
        "---\nname: leftover\ndescription: leftover\nthis-fence-never-closes\n# body\n",
        encoding="utf-8",
        newline="\n",
    )
    rc = _run("init", "claude", "--force")
    assert rc == 0
    out = target.read_text(encoding="utf-8")
    # Fence regex requires a closing `---\n`; missing → defaults restored.
    assert "name: keys-keeper" in out
    assert "macOS Keychain" in out  # default description text
    assert "leftover" not in out
    assert "Storage CLI is `keys`" in out  # canonical body
