#!/usr/bin/env python3
"""Generate the shared admin/WebVault theme-token CSS prefixes."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "scripts" / "ui_theme_tokens.json"
THEME_ORDER = ("evening", "day")
GENERATED_HEADER = (
    "/* Generated by scripts/generate_ui_tokens.py from "
    "scripts/ui_theme_tokens.json. Do not edit this block. */"
)
GENERATED_END = "/* End generated theme tokens. */"
TOKEN_NAME = re.compile(r"^[a-z][a-z0-9-]*$")


def _load_spec() -> dict[str, Any]:
    spec = json.loads(SOURCE.read_text(encoding="utf-8"))
    if spec.get("version") != 1:
        raise ValueError("ui token source must use version 1")
    if tuple(spec.get("themes", {}).keys()) != THEME_ORDER:
        raise ValueError(f"themes must be ordered as {THEME_ORDER!r}")
    if not {"font-ui", "font-mono"} <= set(spec["themes"]["evening"]["tokens"]):
        raise ValueError("the evening theme must define both font stacks")
    for theme_name, theme in spec["themes"].items():
        _validate_declarations(theme_name, theme.get("tokens", {}), custom=True)
    if not spec.get("targets"):
        raise ValueError("at least one CSS target is required")
    return spec


def _validate_declarations(label: str, values: dict[str, Any], *, custom: bool) -> None:
    if not isinstance(values, dict):
        raise ValueError(f"{label} declarations must be an object")
    for name, value in values.items():
        if custom and not TOKEN_NAME.fullmatch(name):
            raise ValueError(f"invalid token name in {label}: {name!r}")
        if not isinstance(value, str) or not value.strip() or ";" in value:
            raise ValueError(f"invalid CSS value for {label}.{name}")


def _render_block(spec: dict[str, Any], target: dict[str, Any], theme_name: str) -> str:
    theme = spec["themes"][theme_name]
    extension = target.get("extensions", {}).get(theme_name, {})
    shared_tokens = theme["tokens"]
    target_tokens = extension.get("tokens", {})
    declarations = extension.get("declarations", {})
    _validate_declarations(
        f"{target['path']}:{theme_name}:tokens", target_tokens, custom=True
    )
    _validate_declarations(
        f"{target['path']}:{theme_name}:declarations", declarations, custom=False
    )
    overlap = set(shared_tokens) & set(target_tokens)
    if overlap:
        raise ValueError(f"target overrides canonical tokens: {sorted(overlap)!r}")

    lines = [f"{theme['selector']} {{"]
    if comment := theme.get("comment"):
        lines.append(f"  /* {comment} */")
    for name, value in (*shared_tokens.items(), *target_tokens.items()):
        lines.append(f"  --{name}: {value};")
    if target_tokens and declarations:
        lines.append("")
    for name, value in declarations.items():
        lines.append(f"  {name}: {value};")
    lines.append("}")
    return "\n".join(lines)


def _render_target(spec: dict[str, Any], target: dict[str, Any]) -> str:
    blocks = [_render_block(spec, target, theme_name) for theme_name in THEME_ORDER]
    return f"{GENERATED_HEADER}\n" + "\n\n".join(blocks) + f"\n{GENERATED_END}\n\n"


def _replace_prefix(current: str, generated: str, path: Path) -> str:
    if not current.startswith(GENERATED_HEADER):
        raise ValueError(f"{path}: generated theme-token header is missing")
    end = current.find(GENERATED_END)
    if end < 0:
        raise ValueError(f"{path}: generated theme-token end marker is missing")
    suffix = current[end + len(GENERATED_END) :].lstrip("\n")
    return generated + suffix


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if a generated CSS prefix differs from the canonical source",
    )
    args = parser.parse_args(argv)

    try:
        spec = _load_spec()
        stale: list[str] = []
        for target_name, target in spec["targets"].items():
            path = (ROOT / target["path"]).resolve()
            if ROOT not in path.parents:
                raise ValueError(f"target escapes repository: {target['path']}")
            current = path.read_text(encoding="utf-8")
            expected = _replace_prefix(current, _render_target(spec, target), path)
            if current == expected:
                continue
            if args.check:
                stale.append(target_name)
            else:
                path.write_text(expected, encoding="utf-8")
                print(f"generated {path.relative_to(ROOT)}")
        if stale:
            print(
                "stale generated UI token CSS: "
                + ", ".join(stale)
                + "; run scripts/generate_ui_tokens.py",
                file=sys.stderr,
            )
            return 1
    except (KeyError, OSError, TypeError, ValueError, json.JSONDecodeError) as exc:
        print(f"ui token generation failed: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
